name: Backend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (ci or fallback)
        run: npm ci --no-audit --no-fund || npm install --no-audit --no-fund

      - name: Node version
        run: node -v

      - name: Run tests (non-blocking until suite added)
        run: npm test || echo "No tests or failing tests (non-blocking for now)"

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    concurrency:
      group: render-deploy
      cancel-in-progress: true
    steps:
      - name: Trigger Render deploy hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "RENDER_DEPLOY_HOOK_URL is not set" && exit 1
          fi
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_URL"

